name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pytest pytest-cov
        
    - name: Lint with Ruff
      run: |
        ruff check .
        ruff format --check .
        
    - name: Run tests with pytest and coverage
      run: |
        pytest tests/ -v --cov=utils --cov-report=term-missing
      env:
        PYTHONPATH: ${{ github.workspace }} 